import express from 'express';
import type { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 8000;
const API_KEY = process.env.API_KEY || 'your_openclaw_key';

// Auth Middleare
const authenticate = (req: Request, res: Response, next: NextFunction) => {
    const authHeader = req.headers.authorization;
    if (authHeader === `Bearer ${API_KEY}` || !API_KEY) {
        next();
    } else {
        res.status(401).send({ error: 'Unauthorized' });
    }
};

app.get('/health', (req, res) => {
    res.send({ status: 'active', service: 'OpenClaw Brain', version: '1.0.0' });
});

// AI Chat Endpoint
app.post('/api/chat', authenticate, async (req, res) => {
    const { message, context } = req.body;

    // Minimal "AI" logic for demonstration
    let response = "";
    if (message.toLowerCase().includes('analyze')) {
        response = "I'm looking into that token for you. Based on the current onchain volume, I see a strong entry point approaching.";
    } else if (message.toLowerCase().includes('long') || message.toLowerCase().includes('short')) {
        response = "Strategic trade confirmed. I've simulated the position and the PnL projection looks favorable for a 5-10x leverage.";
    } else {
        response = "Whistler Agent initialized. I'm monitoring the Base chain for new launches. What's our next move?";
    }

    res.send({ response });
});

// Token Analysis Endpoint
app.post('/api/analyze-token', authenticate, async (req, res) => {
    const { address, ticker } = req.body;

    // Return structured markdown as requested
    const analysis = `
### 🕵️ Token Analysis: ${ticker || address}

**Risk Assessment**: MEDIUM
This token was launched via an AI-deployer pattern. Liquidity is currently locked.

**Onchain Metrics**:
- Holders: 142
- Top 10 Concentration: 12% (Low)
- Volume/Liquidity Ratio: 0.85 (Steady)

**Recommendation**: **LONG**
The agent associated with this token has a high "reputation" score. Consider a 10x position with a 15% stop loss.

*Generated by OpenClaw Autonomous Brain*
`;

    res.send({ analysis });
});

app.listen(PORT, () => {
    console.log(`🧠 OpenClaw Brain running on port ${PORT}`);
});
